### ISSUE TITLE
PHP Fatal error:  Call to undefined function mb_convert_encoding()

### ISSUE THREAD

**Issue by epjuan21** [epjuan21/val4505#1]
Linux AMI
OS: Centos
PHP Version: PHP 5.6.35 (cli) (built: Apr  3 2018 21:27:01) 

[:error] [pid 6070] [client 200.35.47.95:56858] PHP Fatal error:  Call to undefined function mb_convert_encoding() in /var/www/html/val4505/dist/modulos/module.ImportarErroresEcoopsos.php on line 184, referer: http://35.166.203.64/inicio.php?menu=12&CodEPS=EPSS40&CodMun=1&CodUs=1&Per=2018-03-31

**Comment by Norcarde** [comment]
Hola amigo, 
que requisitos previos necesito para probar tu proyecto. o configuración.
Un saludo

**Comment by epjuan21** [comment]
Saludos,

- Tengo el proyecto funcionando en Windows con Laragon, MySQL 5.7.19, PHP 7.2.2.
- Se debe crear la Base de datos llamada val4505.
- El código SQL de las tablas esta en val4505\src\sql\
- El usuario es admin y la contraseña 123
